config/routes.rb
Rails.application.routes.draw do
  root 'site#landing'
  get "dashboard", to: "site#dashboard"
  post "dashboard", to: "site#create"
  get "profile", to: "site#profile"
  get "confirm", to: "site#confirm"

  get "/auth/twitter", as: :login
  get "/auth/twitter/callback", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  namespace :api do
    namespace :v1, defaults: { format: :json } do
      resources :users, only: [:show]
      resources :possibilities, only: [:index]
      resources :lists, only: [:create]
      resources :ideas, only: [:create, :index, :destroy] do
        resources :tweets, only: [:create], module: "ideas"
        resources :possibilities, only: [:index], module: "ideas"
      end
      get "current_idea", to: "ideas#current"
      get "current", to: "users#current"
    end
  end
end

app/views/layouts/_footer.html.erb
<footer class="page-footer footer">
  <div class="footer-copyright">
    <div class="container center">
    Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">JPHoenix</a>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="nav" role="navigation">
  <div class="nav-wrapper container"><%= link_to "Iderator", root_path, id:"logo-container", class:"brand-logo" %>
    <ul class="right hide-on-med-and-down">
      <% if current_user %>
        <li><%= link_to "Welcome " + current_user.name, profile_path %></li>
        <li><%= link_to "Logout", logout_path %></li>
      <% else %>
        <li><%= link_to "Login with Twitter", login_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaGenerator</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
<body>

  <%= render "layouts/navbar" %>

  <main>
    <%= yield %>
  </main>

  <%= render "layouts/footer" %>

</body>

</html>